// src/constants/currencies.js

export const currencies = [
  // 🌏 Asia
  {
    code: "INR",
    symbol: "₹",
    name: "Indian Rupee",
    country: "India",
    display: "Indian Rupee (INR)",
  },
  {
    code: "PKR",
    symbol: "₨",
    name: "Pakistani Rupee",
    country: "Pakistan",
    display: "Pakistani Rupee (PKR)",
  },
  {
    code: "BDT",
    symbol: "৳",
    name: "Bangladeshi Taka",
    country: "Bangladesh",
    display: "Bangladeshi Taka (BDT)",
  },
  {
    code: "LKR",
    symbol: "Rs",
    name: "Sri Lankan Rupee",
    country: "Sri Lanka",
    display: "Sri Lankan Rupee (LKR)",
  },
  {
    code: "NPR",
    symbol: "₨",
    name: "Nepalese Rupee",
    country: "Nepal",
    display: "Nepalese Rupee (NPR)",
  },
  {
    code: "JPY",
    symbol: "¥",
    name: "Japanese Yen",
    country: "Japan",
    display: "Japanese Yen (JPY)",
  },
  {
    code: "CNY",
    symbol: "¥",
    name: "Chinese Yuan",
    country: "China",
    display: "Chinese Yuan (CNY)",
  },
  {
    code: "KRW",
    symbol: "₩",
    name: "South Korean Won",
    country: "South Korea",
    display: "South Korean Won (KRW)",
  },
  {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    display: "Indonesian Rupiah (IDR)",
  },
  {
    code: "THB",
    symbol: "฿",
    name: "Thai Baht",
    country: "Thailand",
    display: "Thai Baht (THB)",
  },
  {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    display: "Malaysian Ringgit (MYR)",
  },
  {
    code: "SGD",
    symbol: "S$",
    name: "Singapore Dollar",
    country: "Singapore",
    display: "Singapore Dollar (SGD)",
  },
  {
    code: "PHP",
    symbol: "₱",
    name: "Philippine Peso",
    country: "Philippines",
    display: "Philippine Peso (PHP)",
  },

  // 🌍 Middle East
  {
    code: "AED",
    symbol: "د.إ",
    name: "UAE Dirham",
    country: "United Arab Emirates",
    display: "UAE Dirham (AED)",
  },
  {
    code: "SAR",
    symbol: "﷼",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    display: "Saudi Riyal (SAR)",
  },
  {
    code: "QAR",
    symbol: "﷼",
    name: "Qatari Riyal",
    country: "Qatar",
    display: "Qatari Riyal (QAR)",
  },
  {
    code: "KWD",
    symbol: "د.ك",
    name: "Kuwaiti Dinar",
    country: "Kuwait",
    display: "Kuwaiti Dinar (KWD)",
  },
  {
    code: "OMR",
    symbol: "﷼",
    name: "Omani Rial",
    country: "Oman",
    display: "Omani Rial (OMR)",
  },
  {
    code: "BHD",
    symbol: ".د.ب",
    name: "Bahraini Dinar",
    country: "Bahrain",
    display: "Bahraini Dinar (BHD)",
  },

  // 🇺🇸 North America
  {
    code: "USD",
    symbol: "$",
    name: "US Dollar",
    country: "United States",
    display: "US Dollar (USD)",
  },
  {
    code: "CAD",
    symbol: "C$",
    name: "Canadian Dollar",
    country: "Canada",
    display: "Canadian Dollar (CAD)",
  },
  {
    code: "MXN",
    symbol: "$",
    name: "Mexican Peso",
    country: "Mexico",
    display: "Mexican Peso (MXN)",
  },

  // 🇪🇺 Europe
  {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    country: "European Union",
    display: "Euro (EUR)",
  },
  {
    code: "GBP",
    symbol: "£",
    name: "British Pound",
    country: "United Kingdom",
    display: "British Pound (GBP)",
  },
  {
    code: "CHF",
    symbol: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    display: "Swiss Franc (CHF)",
  },
  {
    code: "SEK",
    symbol: "kr",
    name: "Swedish Krona",
    country: "Sweden",
    display: "Swedish Krona (SEK)",
  },
  {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian Krone",
    country: "Norway",
    display: "Norwegian Krone (NOK)",
  },
  {
    code: "DKK",
    symbol: "kr",
    name: "Danish Krone",
    country: "Denmark",
    display: "Danish Krone (DKK)",
  },
  {
    code: "PLN",
    symbol: "zł",
    name: "Polish Zloty",
    country: "Poland",
    display: "Polish Zloty (PLN)",
  },
  {
    code: "CZK",
    symbol: "Kč",
    name: "Czech Koruna",
    country: "Czech Republic",
    display: "Czech Koruna (CZK)",
  },
  {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian Forint",
    country: "Hungary",
    display: "Hungarian Forint (HUF)",
  },

  // 🌎 South America
  {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    country: "Brazil",
    display: "Brazilian Real (BRL)",
  },
  {
    code: "ARS",
    symbol: "$",
    name: "Argentine Peso",
    country: "Argentina",
    display: "Argentine Peso (ARS)",
  },
  {
    code: "CLP",
    symbol: "$",
    name: "Chilean Peso",
    country: "Chile",
    display: "Chilean Peso (CLP)",
  },
  {
    code: "COP",
    symbol: "$",
    name: "Colombian Peso",
    country: "Colombia",
    display: "Colombian Peso (COP)",
  },
  {
    code: "PEN",
    symbol: "S/",
    name: "Peruvian Sol",
    country: "Peru",
    display: "Peruvian Sol (PEN)",
  },

  // 🌍 Africa
  {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    country: "South Africa",
    display: "South African Rand (ZAR)",
  },
  {
    code: "NGN",
    symbol: "₦",
    name: "Nigerian Naira",
    country: "Nigeria",
    display: "Nigerian Naira (NGN)",
  },
  {
    code: "EGP",
    symbol: "£",
    name: "Egyptian Pound",
    country: "Egypt",
    display: "Egyptian Pound (EGP)",
  },
  {
    code: "KES",
    symbol: "KSh",
    name: "Kenyan Shilling",
    country: "Kenya",
    display: "Kenyan Shilling (KES)",
  },
  {
    code: "GHS",
    symbol: "₵",
    name: "Ghanaian Cedi",
    country: "Ghana",
    display: "Ghanaian Cedi (GHS)",
  },

  // 🌏 Oceania
  {
    code: "AUD",
    symbol: "A$",
    name: "Australian Dollar",
    country: "Australia",
    display: "Australian Dollar (AUD)",
  },
  {
    code: "NZD",
    symbol: "NZ$",
    name: "New Zealand Dollar",
    country: "New Zealand",
    display: "New Zealand Dollar (NZD)",
  },
];
